// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"XH_Loging","status":true,"description":"加载动画.","parameters":{}},
{"name":"Yami_8DirEx","status":true,"description":"Player can 8-dir move, also touch input movement.","parameters":{"dir4 Switch ID":"100"}}
];
