// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"XH_Loading","status":true,"description":"加载动画.","parameters":{}},
{"name":"XH_plugins","status":false,"description":"窗口插件.","parameters":{}}
];
